search_keywords = [
    'Allergic asthma',
# 'Allergy-induced asthma',
# 'Allergy induced asthma',
# 'Asthma exacerbation',
# 'Asthma flare-ups',
# 'Asthma relapse',
# 'Asthma and COPD',
# 'Asthmatic',
# 'Asthma',
# 'Bronchial Asthma',
# 'Chronic Asthma',
# 'Chronic bronchial asthma',
# 'CBA',
# 'Clinical asthma',
# 'Cough-variant asthma',
# 'CVA',
# 'Difficult to control asthma',
# 'Eosinophilic asthma',
# 'Exercise induced asthma',
# 'Exercise-induced asthma',
# 'Exercise-Induced Bronchoconstriction',
# 'Exercise Induced Bronchoconstriction',
# 'EIB',
# 'Extrinsic asthma',
# 'Heterogeneous asthma',
# 'intermittent Asthma ',
# 'Intrinsic asthma',
# 'Life threatening asthma',
# 'Mild intermittent asthma',
# 'Mild persistent asthma',
# 'Moderate persistent asthma',
# 'Nighttime asthma',
# 'Nocturnal asthma',
# 'Non-atopic asthma',
# 'Non atopic asthma',
# 'Non-eosinophilic asthma',
# 'Non eosinophilic asthma',
# 'Non-smoking asthma',
# 'Non smoking asthma',
# 'Non-T2 asthma',
# 'Non T2 asthma',
# 'Occupational asthma',
# 'Pediatric asthma',
# 'perimenstrual asthma',
# 'PMA',
# 'Pregnancy asthma',
# 'Refractory asthma',
# 'Seasonal asthma',
# 'Severe asthma',
# 'Severe neutrophilic asthma',
# 'Severe persistent asthma',
# 'severe-persistent Asthma ',
# 'Status Asthmaticus',
# 'Stress-induced Asthma',
# 'Stress induced Asthma',
# 'Unusual asthma',
# 'Exercise induced asthma ',
# 'Asthma Attack',
# 'uncontrolled asthma',
# 'moderate asthma',
# 'unresolved asthma',
# 'asthma control',
# 'asthma flare',
# 'asthma follow-up',
# 'exacerbation of asthma ',
# 'brittle asthma',
# 'Exhaled breath analysis',
# 'CT-Scan',
# 'CT Scan',
# 'Lung function tests',
# 'Upper airway examination',
# 'exhaled breath condensate',
# 'EBC',
# 'bronchodilator',
# 'endobronchial biopsy',
# 'Methacholine challenge',
# 'Spirometry',
# 'Peak flow meter',
# 'bronchial biopsy',
# 'sputum neutrophilia',
# 'Skin examination',
# 'Imaging',
# 'bronchoalveolar lavage fluid',
# 'stethoscope examination',
# 'Provocative testing for exercise',
# 'fiberoptic bronchoscopy',
# 'Gastroesophageal reflux assessment',
# 'Sputum analysis',
# 'Phlegm examination',
# 'sputum exam',
# 'Nitric oxide test',
# 'Skin test',
# 'sputum eosinophil counts',
# 'Allergy testing',
# 'Chest X-Ray',
# 'Chest X Ray',
# 'Nose examination',
# 'Physical examination',
# 'Cellular bronchial samples',
# 'Provocative testing- cold-induced asthma',
# 'Lungs X Ray ',
# 'Lungs X-Ray ',
# 'LFT',
# 'skin prick test ',
# 'CCL26',
# 'Arterial blood gas',
# 'ABG',
# 'Asthma screening',
# 'Blood Eosinophils',
# 'Bromotyrosine',
# 'bronchoprovocation',
# 'Bronchoscopic samples',
# 'Challenge test',
# 'Chitinases',
# 'complete blood counts',
# 'C-reactive protein',
# 'C reactive protein',
# 'Dipeptidyl peptidase-4',
# 'DPP4',
# 'EKG',
# 'Electromagnetic Navigational Bronchoscopy',
# 'ENB',
# 'Endobronchial Ultrasound',
# 'EBUS',
# 'Eosinophil cationic protein',
# 'ECP',
# 'eotaxin-2',
# 'FeNO- Fractional nitric oxide',
# 'Fractional Exhaled Nitric Oxide Concentration',
# 'Induced sputum',
# 'Interleukin-17',
# 'lipopolysaccharide-stimulated lipoxin A4 biosynthesis',
# 'Lipoxins',
# 'matricellular protein',
# 'matrix metalloproteinase-9',
# 'MMP-9',
# 'monocyte chemoattractant protein-4',
# 'MCP4',
# 'Periostin',
# 'Pulse oximetry',
# 'serum periostin',
# 'serum urokinase plasminogen activated receptor',
# 'Sputum eosinophil count',
# 'Sputum Eosinophils',
# 'Sputum Neutrophil',
# 'Sputum sample',
# 'Transthoracic needle biopsy',
# 'Tumor necrosis factor α',
# 'tumor necrosis factor-like weak inducer of apoptosis',
# 'urinary bromotyrosine',
# 'BrTyr',
# 'urinary leukotriene E4',
# 'Urine metabolites',
# 'YKL-40',
# 'human cartilage glycoprotein 39',
# 'Airway obstruction',
# 'Lung capacity',
# 'Montelukast',
# 'Singulair',
# 'adrenomimetic drugs',
# 'Advair ',
# 'airway remodelling',
# 'albuterol',
# 'Allergy shots',
# 'Anabolic Steroids ',
# 'Anticholinergics',
# 'Antioxidants intake',
# 'antihistamines',
# 'Asthma diet',
# 'Avoid allergy-triggering foods',
# 'Beclomethasone',
# 'Qvar RediHaler',
# 'Belly breathing',
# 'Benralizumab',
# 'Fasenra',
# 'Nigella sativa',
# 'Breathing exercises',
# 'bronchodilator inhaler',
# 'Budesonide ',
# 'Budesonide',
# 'Pulmicort Flexhaler',
# 'Chiropractic manipulation',
# 'Choline',
# 'Ciclesonide',
# 'Alvesco',
# 'Clarithromycin',
# 'decongestants',
# 'Decontaminate decor',
# 'deep abdominal breathing',
# 'Diaphragmatic breathing',
# 'Dupilumab',
# 'fevipiprant',
# 'Flovent ',
# 'Flovent HFA',
# 'Fluticasone ',
# 'Formoterol ',
# 'Foradil',
# 'HEPA filters',
# 'HFA inhalers',
# 'indacaterol',
# 'Arcapta',
# 'Inhaled corticosteroids',
# 'Inhalers ',
# 'intravenous corticosteroids',
# 'Ipratropium',
# 'Atrovent HFA',
# 'Atrovent',
# 'Ipratropium bromide',
# 'Leukotriene modifiers',
# 'Levalbuterol',
# 'Xopenex HFA',
# 'LABA',
# 'Macrolide',
# 'Mast cell stabilizers',
# 'medicated spray',
# 'mepolizumab',
# 'Nucala',
# 'Methylprednisolone',
# 'Methylxanthines',
# 'Mometasone',
# 'Asmanex Twisthaler',
# 'Omalizumab',
# 'Xolair',
# 'Prednisone',
# 'ProAir HFA',
# 'Progressive muscle relaxation',
# 'Pulmicort ',
# 'Pycnogenol',
# 'reslizumab',
# 'Cinqair',
# 'salmeterol',
# 'Serevent',
# 'Short acting bronchodilators',
# 'Symbicort',
# 'Theophylline',
# 'Ventolin HFA',
# 'vilanterol ',
# 'Zafirlukast',
# 'Accolate',
# 'Zyflo',
# 'Zileuton',
# 'Epipen ',
# 'Diaprhragm Breathing ',
# 'Deap Belly Breathing',
# 'eculizumab',
# 'secukinumab',
# 'fingolimod hydrochloride',
# 'etanercept',
# 'tofacitinib citrate',
# 'esomeprazole magnesium',
# 'tacrolimus',
# 'abatacept',
# 'fluticasone furoate',
# 'vilanterol trifenatate',
# 'risankizumab',
# 'infliximab',
# 'beclomethasone dipropionate',
# 'formoterol fumarate',
# 'golimumab',
# 'umeclidinium',
# 'mometasone furoate',
# 'glycopyrrolate',
# 'canakinumab',
# 'apremilast',
# 'albuterol sulfate',
# 'umeclidinium bromide',
# 'arformoterol tartrate',
# 'roflumilast',
# 'laninamivir octanoate',
# 'fexofenadine hydrochloride',
# 'fluticasone propionate',
# 'indacaterol maleate',
# 'salmeterol xinafoate',
# 'pioglitazone hydrochloride',
# 'levodopa',
# 'aclidinium bromide',
# 'levocetirizine dihydrochloride',
# 'mogamulizumab',
# 'tiotropium bromide',
# 'formoterol fumarate dihydrate',
# 'tezepelumab',
# 'ketotifen fumarate',
# 'rabeprazole sodium',
# 'icatibant acetate',
# 'pranlukast',
# 'glycopyrronium bromide',
# 'olodaterol hydrochloride',
# 'treprostinil sodium',
# 'terbutaline sulfate',
# 'montelukast sodium',
# 'epinephrine',
# 'gefapixant',
# 'brodalumab',
# 'procaterol hydrochloride',
# 'flunisolide',
# 'dexamethasone cipecilate',
# 'beclometasone dipropionate',
# 'ligelizumab',
# 'daclizumab',
# 'doxofylline',
# 'ensifentrine',
# 'itolizumab',
# 'cromolyn sodium',
# 'reproterol',
# 'ibudilast',
# 'tranilast',
# 'oxatomide',
# 'levalbuterol hydrochloride',
# 'clenbuterol hydrochloride',
# 'masitinib mesylate',
# 'suplatast tosylate',
# 'pirbuterol acetate',
# 'pemirolast potassium',
# 'prednisolone',
# 'ozagrel hydrochloride',
# 'abediterol',
# 'adriforant',
'Humira',
'Remicade',
'Soliris',
'Cosentyx',
'Advair',
'Dupixent',
'Symbicort Turbuhaler',
'Simponi',
'Enbrel',
'Xeljanz',
'Nexium',
'Prograf',
'Orencia',
'Pulmicort Respules',
'Otezla',
'Breo Ellipta',
'Skyrizi',
'Foster',
'Flovent',
'Trelegy Ellipta',
'Ilaris',
'Nasonex',
'Veramyst',
'Combivent Respimat',
'Incruse Ellipta',
'Firazyr',
'AcipHex',
'Brovana',
'Atimos',
'Dulera',
'Clenil',
'Alutard',
'Daliresp',
'Breztri Aerosphere',
'Inavir',
'QVAR',
'Allegra',
'Staloral',
'Seebri Neohaler',
'Flutiform',
'Xhance',
'Arcapta Neohaler',
'Actos',
'Inbrija',
'Tudorza Pressair',
'Xyzal',
'Poteligeo',
'DuoResp Spiromax',
'Zaditor',
'Grastek',
'Bufomix Easyhaler',
'Odactra',
'Onon drysyrup',
'QVM149',
'QMF149',
'Rayos',
'Arnuity Ellipta',
'Striverdi Respimat',
'LIQ861',
'Bricanyl Turbuhaler',
'Formatris',
'GB001',
'Primatene Mist HFA',
'Siliq',
'Meptin',
'Aerospan HFA',
'Erizas',
'Aerivio Spiromax/Airexar Spiromax',
'AccuNeb',
'Inspiryl',
'APC-1000',
'Proventil-HFA',
'AirDuo RespiClick',
'Novopulmon Novolizer',
'APC-4000 DPI',
'Zinbryta',
'RPL554',
'XmAb7195',
'Theo-Dur',
'Alzumab',
'Fluticasone & Salmeterol Easyhaler',
'ArmonAir RespiClick',
'Allergospasmin',
'GSK3772847',
'Ketas',
'Rizaben',
'Xopenex',
'Zyflo CR',
'Spiropent',
'Masican',
'IPD-1151T',
'Maxair',
'DuoNeb',
'Sinestic',
'Zetonna',
'APC-5000 DPI',
'Pemilaston',
'RG6149',
'Budesonide Easyhaler',
'Domenan',
'CSJ117',
'AZD5069',
'SAR440340',
'LOU064',
'AZD7594',
'AZD8871',
'AZD1402',
'ZPL389',
'Butyeko',
'Sudation',
'Swedana',
'Virechana',
'Vamana',
'Pranayama',
'laxatives',
'Diskus',
'OT329',
'Advair HFA',
'VR315',
'Prasco',
'Hikma',
'Turbuhaler',
'Diskhaler',
'Revolizer ',
'Breath actuated aerosol inhalers',
'Twisthaler',
'Flexhaler',
'Redihaler',
'Ellipta',
'Neohaler',
'Pressair',
'Breath activated inhalers',
'Accuhalers',
'clickhalers',
'easyhalers',
'novolizers',
'Propeller Health',
'Smart Inhalers',
'LAMA',
'SABA',
'Metered dose inhaler',
'Mometasone',
'formoterol',
'Dulera',
'Dry Powder Inhaler',
'vagotomy',
'Budesonide',
'Symbicort',
'nebulizer',
'chlorofluorocarbon inhalers',
'nasal spray',
'rescue inhaler',
'Fluticasone',
'Advair Diskus',
'salmeterol',
'Fluticasone',
'Breo',
'vilanterol',
'Long-acting bronchodilators',
'cromolyn nasal sprays',
'unilateral resection',
'DPI',
'MDI',
'built-in dose counter',
'ganglionectomy',
'Doser',
'glomectomy',
'Puffers ',
'Soft mist inhaler',
'da Vinci Robotic-assisted Thoracic Surgery',
'CyberKnife Robotic Radiosurgery',
'Video-Assisted Thoracic Surgery',
'AeroChamber',
'pulmonary roots denervation',
'Combination inhalers',
'laryngeal nerve resection',
'Propellant  ',
'Nebulizers',
'Soft mist Inhalers',
'Breath Actuated Inhalers  ',
'Multihaler ',
'Huf Puf Kit ',
'Rotahaler',
'Autohaler ',
'Pre loaded inhaler',
'Aerolizer',
'White Inhalers',
'Blue Inhalers',
'Long-Acting Beta-Agonists',
'Long-acting muscarinic antagonists',
'short-acting beta agonist'
]